### ISSUE TITLE
编辑server时，在左侧同时delete这个server,删除成功后，右侧的编辑页面还在

### ISSUE THREAD

**Issue by pryhub** [VectorSight/Termix-zh_cn#21]

**Comment by wspl** [comment]
这个属于用户体验相关，考虑在 EAP-1.2 中添加

**Comment by pryhub** [comment]
> 这个属于用户体验相关，考虑在 EAP-1.2 中添加
体验么，然后我在点击上面的保存，就直接提示ID不存在[狗头]

**Comment by wspl** [comment]
没考虑到那个服务器是占位符……我标记成 Bug 吧，加个判断，不允许删除作为占位符的服务器
