### ISSUE TITLE
Nightly 通道

### ISSUE THREAD

**Issue by wspl** [VectorSight/Termix-zh_cn#35]
- Nightly 通道，需要对软件本体引入 CI/CD
- 服务器已白嫖到，目前还在研究可行性

**Comment by lijun0326** [comment]
不是很懂为啥要自备服务器，Travis CI这种不行么？支持GitHub私仓（x

**Comment by wspl** [comment]
@lijun0326 价格太贵了，macOS 下的编译还单独卖。不过正好白嫖到了一个 i3 8100 的服务器，明后天去折腾折腾，顺利的话很快就能有 Nightly 通道了。
