### ISSUE TITLE
Windows 下 Explorer 内 Open With 的怪异表现

### ISSUE THREAD

**Issue by kotori2** [VectorSight/Termix-zh_cn#45]
使用Open With-System Default，会调用Notepad++打开文件，然后尝试保存的时候，文件会被上传到服务器两次。如果在NPP里面关掉这个窗口并且再次打开同一个文件的时候，文件会先被NPP打开，然后秒删。重启应用无效，尝试寻找缓存文件也未找到（可能已经被删了）。另外测试的过程中触发过一次“文件无法保存，可能受到保护”，无法复现。

**Comment by wspl** [comment]
nightly-0404 已经尝试修复，我这里测试起来没问题了。如果你那里已经解决麻烦关闭一下这个 issues 以提醒我

**Comment by kotori2** [comment]
刚试了下，没问题啦！
