### ISSUE TITLE
赛门铁克报提醒

### ISSUE THREAD

**Issue by qfdk** [VectorSight/Termix-zh_cn#52]
公司电脑，公司 SEP 报警，多次出现

![Snipaste_2019-04-02_09-50-08](https://user-images.githubusercontent.com/2404478/55385360-3c981580-552d-11e9-8cdb-373805ebfbe4.png)
![Snipaste_2019-04-02_09-51-33](https://user-images.githubusercontent.com/2404478/55385361-3c981580-552d-11e9-845a-4bef39f3c92d.png)

希望处理一下， 应该是软件行为的问题。 为了避免麻烦 公司电脑我先去掉了。

**Comment by wspl** [comment]
winpty-agent 是 local terminal 的依赖程序，建议加入信任名单

**Comment by qfdk** [comment]
> winpty-agent 是 local terminal 的依赖程序，建议加入信任名单

个人没有权限，会被警报，公司处理是这样的，个人没有权限。

**Comment by tobyxdd** [comment]
这个是你公司设置的规则 没见过的程序一律警告 你看提示就知道了并不是报毒 只是说这个程序在它数据库里没见过 我们这是新软件还没大规模发布肯定是这样的 这个没有办法

**Comment by wspl** [comment]
@tobyxdd vscode jetbrains 之类的也都依赖这个东西，估计是我这个版本太新了

**Comment by wspl** [comment]
因为开发过程中会不断引入新的依赖，向安全软件生产商提交样本效率低而且没有意义，所以我们在正式发售前不会去主动解决与安全软件有关的问题，故先暂时将这个问题关闭。
