### ISSUE TITLE
代理服务器bug

### ISSUE THREAD

**Issue by baobao1270** [VectorSight/Termix-zh_cn#62]
操作系统：Windows 10 Home 1809 64-bit
版本：Nightly 20190404
问题：在 Perference —— Network —— Proxy Settings 中，Disable/Enable 按钮点了没用。

**Comment by wspl** [comment]
目前无法复现，等待第二个出现此 Bug 的用户。

建议删除配置文件试试，配置文件 Windows 在 `%appdata%/Termix`，macOS 在 `~/.termix`

删除配置文件会导致所有服务器被删除，建议备份一份之后再删除。

**Comment by baobao1270** [comment]
删除配置文件后，bug解决。
似乎是windows的权限问题，在ghost后的windows上，用户目录权限有文旅
