### ISSUE TITLE
nightly版本无法保存配置

### ISSUE THREAD

**Issue by CptTZ** [VectorSight/Termix-zh_cn#68]
在使用`htop`时，按`Page Up`或者`Page Down`是会卷动列表的，在Termix下，按这两个键没有反应。

**Comment by wspl** [comment]
临时解决方案：
尝试在 `Preferences - Keymap - Terminal` 下，删掉 `Scroll Page Up` 和 `Scroll Page Down` 两个快捷键的绑定（右键菜单中删除）。

若无效再 @ 我

**Comment by CptTZ** [comment]
删除后有效了。
但是刚刚发现`nightly-20190406`版本无法保存配置？

**Comment by wspl** [comment]
具体是指什么配置无法保存？是重开程序后配置丢失还是？

**Comment by CptTZ** [comment]
所有配置丢失，需要重新登录

**Comment by wspl** [comment]
@CptTZ 能否提供一下 %appdata%/Termix 目录下的截图，包括 local*.db 两个文件详细的创建日期和修改日期的

**Comment by CptTZ** [comment]
并没有.db文件，而且目录没有权限问题。
![a1](https://user-images.githubusercontent.com/5669264/55677341-68a7f380-58ab-11e9-99cb-07918d46c0fb.jpg)
![a2](https://user-images.githubusercontent.com/5669264/55677342-68a7f380-58ab-11e9-9b3a-9c9412c743ea.jpg)

**Comment by wspl** [comment]
已定位到问题，是这个 nightly 版本的一个严重 Bug。
今天稍晚会发布一个修复后的版本。

**Comment by CptTZ** [comment]
Thanks, awaiting update
